// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.166
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ImageSpritesVsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "0c4c1075-3865-436a-925a-7b97a641c9e0";
        public const string guidImageSpriteCmdSetString = "ad408e80-5054-4184-b141-830702b6346c";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidImageSpriteCmdSet = new Guid(guidImageSpriteCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MenuGroup = 0x1020;
        public const int CreateSprite = 0x0100;
        public const int UpdateSprite = 0x0200;
    }
}
