// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ImageSpritesVsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "cd92c0c6-2c32-49a3-83ca-0dc767c7d78e";
        public const string Name = "Image Sprites";
        public const string Description = @"Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.";
        public const string Language = "en-US";
        public const string Version = "1.4";
        public const string Author = "Mads Kristensen";
        public const string Tags = "image, sprite, jpg, gif, png, css, stylesheet, stylus, less, sass, scss";
    }
}
